import Head from 'next/head'
import React, { ReactNode } from 'react'
import PfrNavigation from '../Modules/Epfrs/CreateData/PfrNavigation'
import SubmissionNavigation from '../Modules/Submissions/CreateData/SubmissionNavigation'
import Sidebar from './Sidebar/Sidebar'


interface Props {
    children?: ReactNode,
    typeMenu?: any
  }

const AppSecondaryLayout = (prop: Props) => {
  return (
    <>
      <Head>
        <title>Unicorn Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-row w-full min-h-screen font-sans bg-white'>
        <Sidebar />

        {/* {prop.typeMenu == "1" ? <PfrNavigation /> : <SubmissionNavigation />} */}
        {prop.children}
      </div>
    </>
  )
}

export default AppSecondaryLayout