import Head from "next/head";
import React, { ReactNode, useEffect, useState } from "react";
import Sidebar from "./Sidebar/Sidebar";

interface Props {
  children?: ReactNode;
  typeMenu?: any;
}

const AppSecondaryLayout = (prop: Props) => {
  const [isHydrated, setIsHydrated] = useState(false);

  // Wait till Next.js rehydration completes
  useEffect(() => {
    setIsHydrated(true);
  }, []);

  return (
    <>
      <Head>
        <title>Unicorn Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-row w-full min-h-screen font-sans bg-white">
        {isHydrated ? <div>{prop.children}</div> : null}
      </div>
    </>
  );
};

export default AppSecondaryLayout;
