import Head from "next/head";
import React, { ReactNode } from "react";
import Sidebar from "./Sidebar/Sidebar";

interface Props {
  children?: ReactNode;
}

const DashboardLayout = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Epfr Lite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-row w-full min-h-screen font-sans bg-white">
        <Sidebar />
        {children}
      </div>
    </>
  );
};

export default DashboardLayout;
