// Generated by https://quicktype.io
interface Product {
    selected:                   boolean;
    edit:                       boolean;
    subjectId:                  number;
    name:                       string;
    type:                       number;
    productType:                number;
    id:                         number;
    categoryId:                 number;
    policyTerm:                 string;
    sumAssured:                 string;
    premiumPaymentType:         string;
    premium:                    number;
    premiumFrequency:           number;
    funds:                      any[];
    modelPortfolioRiskCategory: number;
    higherThanRiskProfile:      number;
    nameOfOwner:                number;
    nameOfInsure:               string;
    nameOfInsureOther:          string; 
    currency:                   string; 
    benefit:                    Benefit[];
    risk:                       Risk[];
    portfolio:                  number;
    fundName:                   string;
    fundAmount:                 number;
    premiumForHospitalization:  PremiumForHospitalization;
    groupId:                    number;
    premiumType:                number;
    feature:                    null;
}

interface Benefit {
    benefitId: number;
    title:     string;
    content:   string;
}

interface PremiumForHospitalization {
    cash:        number;
    cpfMedisave: number;
}

interface Risk {
    riskId:  number;
    title:   string;
    content: string;
}

export interface SectionNineRecommendation {
    section9Recommend: {
        groupId:     number;
        pfrId:       number;
        product:     Product;
        riders:      any[];
        extraRiders: any[];
    }
}
